- README.md
- eureqa.jl
- eureqa.py
- hyperparamopt.py
- operators.jl
Insertion op:
- Insert random operator inside an equation at a random node, rather than just at a leaf. Binary trees will add a new constant/variable on one of their branches.
Deletion op:
- Now when deleting an operator from the middle of an equation, it will leave the enclosed operations, rather than replacing them with a constant/variable.
Simplification op:
- ((x0 + const) + const)=>(x0+const), and ((x0 * const) * const) => (x0 * const) after initially simplifying all constant parts of an equation, like (const ... const) => (const). This seems to help a lot with the new insertion op, which seemed to result in many constants being added together.
Hyperparams:
- These have been set to hand-chosen values until a new hyperparameter optimization is run.
> Add insertion op; improve deletion op; add new way to simplify constants

- pysr/sr.py
This PR adds preliminary feature selection based on gradient boosting trees. The user supplies the argument "select_k_best," and scikit-learn's GBTR is used to train on (X, y), which is then used to calculate feature importances for X. The best `k` features are then used in the symbolic regression algorithm.
Later on it would be nice for this to be done on the Julia side, and used recursively to find the best features at the mutation stages of the symbolic regression. But this is a simple approach for selection of features from the initial `pysr` call.
> Add feature selection based on gradient boosting

- pysr/sr.py
This PR adds support for running PySR on Windows, fixing #17.
> Windows support

- Project.toml
- docs/options.md
- example.py
- pysr/sr.py
- setup.py
This will move PySR to v0.5.0 of SymbolicRegression.jl (once that version is added to the registry).
This also enables custom loss functions via the `loss` kwarg. One can define a loss using the functions available (e.g., `L2DistLoss()` or `L1DistLoss()`), or pass a function definition like this:
```
pysr(..., loss="myloss(x, y) = abs(x - y)")
```
or, for weighted, e.g.,
```
pysr(..., loss="myloss(x, y, w) = abs(x - y) * w")
```
This is slower than using the built-in losses but more convenient for defining new ones.
> Custom loss functions - v0.5.0

- Project.toml
- pysr/sr.py
- test/test.py
This will allow one to pass a matrix for y, and the backend will batch an equation search, and return equations for each output. This is much faster than running PySR once for every output, and of course, more convenient.
Fixes #35 and #45.
> Multi-output y / batched equation search

- .github/workflows/CI.yml
- pysr/__init__.py
- pysr/export_jax.py
- pysr/export_torch.py
- pysr/sr.py
- test/test_jax.py
- test/test_torch.py
This uses (a slightly-modified version of) @patrick-kidger's [sympytorch](https://github.com/patrick-kidger/sympytorch) to export discovered equations to PyTorch. Parameters in the module are set to the default as found by PySR, but are trainable.
This essentially allows one to do the deep learning -> symbolic regression technique from https://github.com/MilesCranmer/symbolic_deep_learning, but plug the discovered equation back into the network, without any manual work.
This is the same format as the JAX export - it expects a matrix `X` as input with columns corresponding to symbols, except it outputs a PyTorch module with embedded parameters instead of a (function, parameters) tuple.
@patrick-kidger, what do you think of this way of doing things? The modifications from your package …
> PyTorch export

- Project.toml
- setup.py
The update applied to the backend updating SymbolicUtils.jl to 0.13 (used in 0.6.11 onwards) in https://github.com/MilesCranmer/SymbolicRegression.jl/pull/37 unfortunately introduced several (subtle, stochastic) issues, so I am reverting this change in PySR (won't affect the Julia standalone) until the refactored backend has stabilized. Two issues caused by the refactoring have been fixed, but I don't want other such issues to show up to new users.
> Revert unstable Symbolics update in backend

- .github/workflows/CI.yml
- .github/workflows/CI_Windows.yml
- .github/workflows/CI_conda.yml
- .github/workflows/CI_mac.yml
- .gitignore
- Dockerfile
- Project.toml
- README.md
- docs/start.md
- environment.yml
- pysr/__init__.py
- pysr/feynman_problems.py
- pysr/sr.py
- requirements.txt
- setup.py
- test/test.py
- test/test_static_libpython_warning.py
This switches the entirety of the Julia/Python interface to use PyJulia rather than a `subprocess` call to a generated script. Multithreading and distributed computing both work! 
This brings several advantages:
- Huge speedups in startup time on second `pysr( )` calls in the same python call
- Simplified error debugging on the Julia side
- Greatly simplified codebase with no huge chunks of code generation
- Possibility to checkpoint the symbolic regression search, and restart later
The disadvantage is that this will put PySR at the mercy of PyJulia and any bugs that it experiences. However, I think in the longterm this is still much better than running a script of generating code.
Installation with this new interface is now:
```bash
pip install pysr
python -c 'import pysr; …
```
> Switch Julia interface to PyJulia

- pysr/sr.py
- setup.py
See https://github.com/MilesCranmer/SymbolicRegression.jl/issues/59 for a discussion.
This also:
- lowers the default simplification frequency by 5x which seems to speed up the searches a bit.
- Runs `Pkg.instantiate()` regardless of whether `update=True` or `False`. This will enforce that the correct version of SymbolicRegression.jl is used.
> Reverts to SymbolicUtils.jl v0.6 to temporarily fix the simplification backend

- pysr/sr.py
- test/test.py
By passing, for example, `model.predict(X, index=2)`, you will perform a prediction using the 2nd equation in the internal `model.equations` dataframe. You can view the index of each expression by running `print(model)`, or simply looking at `model.equations`.
This allows the user to specify their own model selection strategy, and is quite a simple change to the codebase. It also works for the sympy, latex, pytorch, and jax export functions–simply by changing the argument of `.get_best` to have a row kwarg.
> Add mechanism to manually do model selection

- pysr/export_jax.py
- pysr/export_torch.py
Sometimes SymPy will create weird functions when evaluating a string (even without running `.simplify()`, such as `sympy.core.numbers.One` (for exact 1) and `sympy.core.numbers.Half` (exact 1/2).
This adds those functions to the JAX and PyTorch. This also adds the heaviside function, which is useful when searching the space of branched functions (like an if statement).
> Add mappings from sympy exact One/Half

- pysr/sr.py
- pysr/version.py
This let's PySR launch jobs over a cluster. If you are on a slurm cluster (on the head node of a job), you simply pass `cluster_manager="slurm"` to PySRRegressor, and it will set up a bunch of workers over the slurm job. Likewise, the other cluster managers listed on https://github.com/JuliaParallel/ClusterManagers.jl can be used.
The one unfortunate thing is I don't think this functionality can be unit-tested; it will just be manual tests on clusters.
cc @KazeWong!
> Enable custom cluster managers

- pysr/sr.py
- pysr/version.py
There are now several stop conditions for a PySR search.
1. `niterations` - PySR will exit after the set number of iterations have passed.
2. `timeout_in_seconds` - exit based on clock time.
3. `max_evals` - exit after a certain number of evaluations have occurred. (**NEW**)
4. `early_stop_condition` - exit after a certain loss has been met. (**NEW**)
5. Manually hitting `q` or `<ctl-c>` and then enter during the search, if you are using it interactively.
> New exit strategies: max_evals and early_stop_condition

- pysr/sr.py
- pysr/version.py
- test/test.py
This adds the options introduced in https://github.com/MilesCranmer/SymbolicRegression.jl/pull/105.
For example:
```python
model = PySRRegressor(
...
complexity_of_operators={"sin": 3, "exp": 5, "+": 1},  # Default is 1 per operator
complexity_of_constants=2,  # Default 1
complexity_of_variables=3,  # Default 1
)
```
would make an expression like:
```
sin(x1 + 3.2 * exp(2.1))
```
have a complexity of 3+3+1+2+1+5+2 = 17, rather than simply 1+1+1+1+1+1+1 = 7.
(Also works for custom operators)
> Allow custom complexities for operators, constants, and variables

- pysr/export_jax.py
- pysr/export_numpy.py
- pysr/sr.py
- pysr/version.py
- test/test.py
- test/test_jax.py
- test/test_torch.py
Re Issue #143
Compatibility with scikit-learn should be improved. 
Noteable breaking changes for users: `PySRRegressor.equations` is now called `PySRRegressor.equations_`
Tests have been updated to allow compatibility with the refactored code but still assess the same functionality. All tests should pass.
Please let me know if there are any concerns or if you would like me to document/explain any of the changes in detail.
> Refactor of PySRRegressor

- .gitignore
- README.md
- pysr/__init__.py
- pysr/sr.py
- test/test.py
- test/test_jax.py
This makes it easier to load models directly from a saved equation file. There are two ways to use this:
1. You can use `pysr.load(...)` to load from a standalone csv file of equations. However, you must pass a few different attributes here, to initialize the model: `binary_operators`, `unary_operators`, and `n_features_in`. If you have custom variable names, you also need to pass that, as well as `nout` if the number of outputs is not 1.
2. `PySRRegressor` will now automatically create a pickle file of the model parameters when running `fit(...)`. This has the same name as the equation file, but with a `.pkl` extension. This lets you run, e.g., `pysr.load("equations.csv")`, and have everything loaded from the equation. This also loads all the other parameters. (Although, you also need to …
> [Feature] Easy loading from equation file

- pysr/sr.py
- pysr/version.py
- test/test.py
- test/test_jax.py
- test/test_torch.py
This is a long-desired change to the checkpoint format. Rather than "|" separators, which was used because "," appears inside the equation, this simply assumes the equation column is surrounded by quotations - which deactivates the commas.
For example,
```
Complexity|MSE|Equation
1|0.19951081|1.9762075
3|0.12717344|(f0 + 1.4724599)
4|0.104823045|pow_abs(2.2683423, cos(f3))
```
is now:
```
Complexity,Loss,Equation
1,0.19951081,"1.9762075"
3,0.12717344,"(f0 + 1.4724599)"
4,0.104823045,"pow_abs(2.2683423, cos(f3))"
```
which will correctly preview on various systems without having to specify the separator.
Fixes #120
> Switch to comma-based csv format

- pysr/sr.py
- test/test.py
In PySR `v0.10.0`, this should change the definition of `model_selection="best"` to also include a loss threshold. Sometimes, just returning the equation with the max score will have a very bad loss - perhaps because a very simple equation just happens to have a large derivative in the loss-complexity curve. 
This PR changes this so that only equations with `loss < 1.5 * min_loss` are considered. This is what was used by PySR in the GECCO contest and seemed to work well in that situation.
To select purely based on score, one can now use `model_selection="score"`
This PR also refactors the model_selection to avoid shotgun edits.
> Change "best" model_selection to include a loss threshold

- pysr/export_latex.py
- pysr/sr.py
- test/test.py
This generates a booktabs-style LaTeX table for a subset of equations. Here is an example:
```python
import numpy as np
from pysr import PySRRegressor
X = 2 * np.random.randn(100, 5)
y = 2.5382 * np.cos(X[:, 3]) + X[:, 0] ** 2 - 0.5
model = PySRRegressor(
niterations=80,
binary_operators=["+", "*"],
unary_operators=["cos"],
model_selection="best",
loss="loss(x, y) = (x - y)^2",  # Custom loss function (julia syntax)
maxsize=11,
)
model.fit(X, y)
print(model.latex_table(precision=3, include_score=True))
```
The output of this is:
```latex
\begin{table}[h]
\begin{center}
\begin{tabular}{@{}lccc@{}}
\toprule
Equation & Complexity & Loss & Score \\
\midrule
$3.9$ & 1 & 38.9 & 0 \\
$x_{0}^{2}$ & 3 & 3.16 & 1.26 \\
$x_{0}^{2} - 0.257$ & 5 & 3.09 & 0.0105 \\
$x_{0}^{2} + \cos{\left(x_{3} …
```
> [Feature] LaTeX table generator

- pysr/julia_helpers.py
- pysr/sr.py
* Sets `JULIA_PROJECT` before loading pyjulia so that PyCall.jl can be contained within the pysr environment
* Also use `Pkg.add` in a single step to add both SymbolicRegression.jl and ClusterManagers.jl to the environment at the same time
I likely advised against using the environment variable `JULIA_PROJECT` in the past. However, I think this may be necessary to avoid interference from other projects if installed within the same environment.
> Set JULIA_PROJECT, use Pkg.add once

- .github/workflows/CI_Windows.yml
- pysr/julia_helpers.py
- pysr/sr.py
If the Julia project is a shared env, the variable `JULIA_PROJECT` will only be set to `@pysr-{version}` if Julia >= 1.7. Otherwise, it will not be set, and the activation performed explicitly.
This also includes a cleaner version check which doesn't require Julia to be started.
@mkitti do you think you could take a look at this?
> Fix install for Julia <=1.6

- pysr/julia_helpers.py
This explicitly deprecates Julia <= 1.5 for new PySR installations. Julia 1.5 is incompatible with some of the latest backend dependencies, so this gives a helpful error message, rather than letting the user read the `Pkg` compat issue printout.
> Explicitly deprecate Julia <= 1.5

- .github/workflows/CI.yml
- .github/workflows/CI_Windows.yml
- .github/workflows/CI_conda_forge.yml
- .github/workflows/CI_docker.yml
- .github/workflows/CI_docker_large_nightly.yml
- .github/workflows/CI_large_nightly.yml
- .github/workflows/CI_mac.yml
- environment.yml
- pysr/julia_helpers.py
- test/test_env.py
This will fix #196. If you specify an `@` in your `julia_project` string, like `julia_project="@my_project"`, then this will be designated a shared project (just as if you had specified `]activate @my_project` in the Julia REPL.
cc @mkitti
> Allow custom shared projects for `julia_project`

- .github/workflows/CI_conda_forge.yml
- pysr/sr.py
- pysr/version.py
This will change the default behavior of PySRRegressor to **not** update the Julia packages when `.fit` is called. i.e., this will set `update=False` by default, rather than `update=True`. I think this is more in line with what a user would expect - that once they install PySR and run `pysr.install()`, all packages will remain static.
It is also causing trouble for conda-forge, since the pysr package actually includes all dependencies when first built - if any new dependency is needed, then pysr will break. This fixes #201. cc @ngam.
To update Julia packages, in pip or in conda, you may run `pysr.install()` again, or set `update=True`.
TODO:
> Fix conda forge installs

- pysr/julia_helpers.py
- pysr/sr.py
- pysr/version.py
This PR updates the backend with faster evaluation: https://github.com/MilesCranmer/SymbolicRegression.jl/pull/144
The latest version of SymbolicRegression.jl also includes a constant parameter `PACKAGE_VERSION`, which allows PySR to assert that the correct version was loaded. This will help prevent unexpected errors caused by an installation for some reason being out-of-date with what PySR expects.
This is just a warning, so it won't necessarily prevent running with a custom backend version if needed.
> Faster evaluation & perform explicit version assertion for backend

- pysr/sr.py
- pysr/version.py
- test/test.py
This updates the backend to v0.14, which has a `turbo` parameter. Turning this on uses `LoopVectorization.jl` on the operators, which can get ~30% performance improvement compared to the current evaluation mechanism.
> Speed up evaluation with `turbo` parameter

- pysr/version.py
- test/test.py
This lets you use `turbo=True` with operators like `sqrt`, `pow`, etc., which need to use unsafe versions inside SIMD kernels.
> Fixed safe operators; make progress bar print to stderr

- .github/workflows/CI_docker.yml
- .github/workflows/CI_docker_large_nightly.yml
- Dockerfile
- README.md
This PR:
- Now sets `org.opencontainers.image.version` based on the actual installed PySR version, rather than a user-passed arg.
- Uses whatever architecture the user has by default; though you can change it with `--platform` (rather than `--build-arg`).
- Expands testing to `arm64`.
> Clean up dockerfile

- docs/param_groupings.yml
- pysr/julia_helpers.py
- pysr/sr.py
- pysr/test/test.py
- pysr/version.py
cc @mkitti 
I have `optimize=3`, but not sure if that's a safe default or not. I wouldn't expect any user to find `julia_kwargs` though, so I'm leaning towards choosing the fastest option as a default if I don't expect it to increase crashes.
> Make Julia startup options configurable; set optimize=3

- Dockerfile
No more manually pulling the Julia binary in a script, it turns out you can just pull from both the python and julia images, and copy the files between them!
This cleans up the dockerfile, and should make it much more robust.
> Make docker build multi-stage

- .github/workflows/docs.yml
- docs/interactive-docs.md
- docs/requirements.txt
- mkdocs.yml
Essentially looks like this:
https://user-images.githubusercontent.com/7593028/212496152-4f315e8f-240a-4ca7-a2ac-906e551d2682.mov
but with added docs-on-hover for each option. 
Will be a new page in the docs dedicated to the interactive version.
> Create interactive API reference page

- .github/workflows/CI.yml
- .github/workflows/CI_Windows.yml
- .github/workflows/pypi_deploy.yml
- examples/pysr_demo.ipynb
- pysr/julia_helpers.py
- pysr/version.py
On systems where compiled modules are disabled, it doesn't make sense to run the precompilation. This adds the option:
```python
pysr.install(precompile=False)
```
this will also automatically set `precompile=False` on systems with static binaries, where compiled modules can't be used anyways.
> Make precompilation optional

- pysr/version.py
There was a bug noted in https://github.com/MilesCranmer/SymbolicRegression.jl/pull/171. This PR includes that fix into PySR.
This will result in modest speed improvements for default settings, and massive speed improvements when parsimony is set to zero. However, it may change behavior slightly, as now the algorithm is not allowed to explore above the maximum size, ever.
> Update backend with constraints fix

- docs/examples.md
- pysr/__init__.py
- pysr/sklearn_monkeypatch.py
- pysr/sr.py
- pysr/test/test.py
- pysr/version.py
This enables PySR to search for complex-valued expressions. Now, if you pass complex data, it will automatically search for complex expressions.
Specifying `precision=32` (default) will use `complex64` and `precision=64` will use `complex128`.
For example:
```python
import numpy as np
from pysr import PySRRegressor
X = np.random.randn(100, 3) + 1j * np.random.randn(100, 3)
y = (2 + 1j) * np.cos(X[:, 0] * (0.5 - 0.3j))
model = PySRRegressor(binary_operators=["+", "-", "*"], unary_operators=["cos"])
model.fit(X, y)
```
we can look at the best expression with:
```python
model.sympy()
```
this gives me:
```
(2.0000386 + 1.0000093*I)*cos(x0*(0.49999392 - 0.2999942*I))
```
---
The one downside of this change is I have to monkey patch scikit-learn at runtime, because their `BaseEstimator` class …
> Complex-valued expressions

- docs/examples.md
- docs/param_groupings.yml
- pysr/sr.py
- pysr/test/test.py
- pysr/version.py
Right now, a user can only specify a custom elementwise loss function. This change allows the user to customize the entire objective function, including:
- Correlation or whole array-based losses (fixes https://github.com/MilesCranmer/PySR/issues/182, https://github.com/MilesCranmer/PySR/discussions/270, https://github.com/MilesCranmer/PySR/discussions/256).
- Objectives that include symbolic manipulation (fixes https://github.com/MilesCranmer/PySR/discussions/275). See below for a cool example.
- Objectives that have symbolic-based regularizations, like soft penalties on symbolic constraints, rather than hard penalties.
Here's a cool example that let's you fix a symbolic form of an expression, as a rational function (i.e., $P(X)/Q(X)$ for polynomials $P$ and $Q$).
```python
objective = …
```
> Allow user to specify full objective functions

- pysr/sr.py
- pysr/version.py
Fixes #395.
The default Julia encoding is UTF-8, so the writing seems fine.
However, apparently Python has different encodings for _reading_ on different architectures, which is why it can break sometimes. The fix is to always assume UTF-8 in reading the equation file.
> Ensure files are read as utf-8 on all operating systems

- pysr/sr.py
- pysr/test/test.py
- pysr/version.py
It is a common mistake users seem to make that they allow for power laws without setting any constraints on complexity of their arguments. This change will trigger a warning when this happens, and also point the user to the docs for more information.
> Warn user when using power laws

- pysr/export_sympy.py
To overcome the sympy bug while using Min/Max operators as discussed under this issue: https://github.com/MilesCranmer/PySR/issues/183
Fixes #183
> Added "min" and "max" sympy mapping

- pysr/export_sympy.py
Enabling a workaround to avoid the following type error:
`raise TypeError("Cannot round symbolic expression")`
while using `round` as a unary operator.
This issue was raised in #269 the the PR contains the exact solution that was put forth in the subsequent discussion.
> Added "round" operator in the Sympy mappings

- pysr/__init__.py
- pysr/version.py
I'm experiencing a lot of segfaults on Python 3.12. See https://github.com/JuliaPy/PyCall.jl/issues/1072 for updates.
Until this is resolved this PR will make PySR raise a warning on any post-3.12.0 version of Python recommending the user to downgrade Python.
> Warn the user on Python 3.12

- .github/workflows/CI.yml
- .github/workflows/CI_Windows.yml
- .github/workflows/CI_docker_large_nightly.yml
- .github/workflows/CI_mac.yml
- .github/workflows/docker_deploy.yml
- Dockerfile
- pysr/export_latex.py
- pysr/sr.py
- requirements.txt
- setup.py
Since `typing.Literal` doesn't exist on Python 3.7, we need to install `typing_extensions` for such older versions.
Also updates the CI to test Python 3.7 & 3.11, and Julia 1.6 & 1.10
> Install `typing_extensions` for compatibility with Python 3.7

- pysr/juliapkg.json
Fixes #561. Julia (actually libgomp) has a bug on 1.10.1 and 1.10.2 that causes a segfault on some RHEL distributions. So this skips those bad Julia versions.
More info: https://github.com/JuliaLang/julia/pull/53643
> Limit to Julia 1.6.7-1.10.0 and 1.10.3+

- pysr/julia_extensions.py
- pysr/julia_import.py
It seems like package extensions were not actually being installed in the PySR environment if the user happened to have those packages installed in their primary (e.g., `@v1.10`) environment, as the `try catch` wouldn't hit the `catch` statement.
This led to issues because worker processes are loaded directly into the PySR environment, and cannot import packages from the primary environment!
> Fix extensions not being added to package env

- docs/examples.md
The discovered equation is indeed a small epsilon from the original equation, but there's a typo in the denominator in the latex simplification.
> Fix sign typo in example docs

- pysr/sr.py
- pysr/test/test.py
PySRRegressor has a lot of parameters. To help with this, this PR implements an "autosuggestion" feature that, upon receiving an invalid keyword, will print an error message with possibilities for what the user had meant to write out.
```python
In [2]: model = PySRRegressor(iterations=10)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[2], line 1
----> 1 model = PySRRegressor(iterations=10)
File ~/PermaDocuments/SymbolicRegressionMonorepo/PySR/pysr/sr.py:916, in PySRRegressor.__init__(self, model_selection, binary_operators, unary_operators, niterations, populations, population_size, max_evals, maxsize, maxdepth, warmup_maxsize_by, timeout_in_seconds, constraints, …
```
> Automatically suggest related keywords

- .github/workflows/CI.yml
- README.md
- pyproject.toml
- pysr/juliapkg.json
- pysr/sr.py
- pysr/test/params.py
- pysr/test/test.py
- pysr/test/test_jax.py
- pysr/test/test_startup.py
- pysr/test/test_torch.py
- pysr/utils.py
This allows you to specify different complexities for each variable.
This also updates the backend with various improvements.
> Per-variable custom complexities

- Dockerfile
- pysr/export_jax.py
- pysr/export_sympy.py
- pysr/export_torch.py
- pysr/test/test.py
- pysr/test/test_jax.py
- pysr/test/test_torch.py
Fixes #656 by @tbuckworth
This is also the "right thing to do" for other reasons. `sympify` shouldn't simplify automatically, the user should do it explicitly, otherwise they might be surprised by it being different. Avoiding automatic simplification also reduces the need for extra sympy mappings.
Also adds `sympy.NumberSymbol` support in both sympy2jax and sympy2torch with new tests.
> BREAKING: Disable automatic sympy simplification

- .github/workflows/CI_apptainer.yml
- Apptainer.def
- pyproject.toml
- pysr/test/test_startup.py
fix: 686
This pull request adds an Apptainer definition file to PySR. Researchers can use it to build an Apptainer container that packages PySR and its dependencies (via a conda environment).
> Apptainer definition file for PySR

- environment.yml
- pysr/sr.py
- requirements.txt
https://github.com/JuliaPy/PythonCall.jl/issues/537
Strangely the new GC of PythonCall seems to cause hanging precompilation. I'm not exactly sure why.
> deps: downgrade PythonCall due to hanging precompilation

- requirements.txt
Hopefully the fix in https://github.com/JuliaPy/PythonCall.jl/pull/544 is enough to fix https://github.com/JuliaPy/PythonCall.jl/issues/537
Closes #695
> JuliaCall 0.9.23

- pysr/logger_specs.py
- pysr/sr.py
- pysr/test/test_main.py
Hallo,
I have added an abstract 'dummy' method to close the logger in instance to AbstractLoggerSpec and a method with the same function for the TensorboardLoggerSpec. The method is called in sr.py after the logging file is completed. This enables the use of the parameter overwrite = True for the TensorBoardLoggerSpec and solves issue (Closes #761) .
Best regards
> logger fixes: close streams and persist during warm start

- .github/workflows/CI_apptainer.yml
- pysr/julia_import.py
- pysr/juliapkg.json
- pysr/param_groupings.yml
- pysr/sr.py
Also fixes #779 and fixes #757. 
Also includes various improvements to memory allocations.
> feat: add differential operators and input stream specification

- docs/examples.md
- docs/operators.md
- pyproject.toml
- pysr/juliapkg.json
Adds the updates for `atanh_clip` => `safe_atanh` as well as fixed derivatives for the safe operators.
Also adds a differential search example.
Also improves the operators page.
> Backend 1.5.0

- .github/workflows/update_backend_version.py
- docs/examples.md
- pysr/expression_specs.py
- pysr/juliapkg.json
- pysr/param_groupings.yml
- pysr/sr.py
- pysr/test/test_main.py
Includes parametric form of template expressions as well as `loss_function_expression` for custom loss functions on whole expression objects.
This is part of the v1.7 update to the backend: https://github.com/MilesCranmer/SymbolicRegression.jl/releases/tag/v1.7.0
> Parametric template expressions

- pyproject.toml
- pysr/juliapkg.json
- pysr/sr.py
There is a slight behavioural changes here:
**New mini batches are sampled less frequently**. It now resamples only every iteration; rather than every eval - see MilesCranmer/SymbolicRegression.jl#421. This result in a speed improvement for code with `batching=true`. It should also result in improved search results, because comparison within a single population is more stable during evolution. In other words, there are no longer expressions that are ranked highly in the local population due to a "lucky batch"
Note that other than the slight behaviour change, this is otherwise backwards compatible - the old way to write custom loss functions that take indices will still be handled normally, without warnings or errors.
However, now you no longer have to write the fourth `idx` argument in …
> Update backend to v1.8.0

- pysr/__init__.py
- pysr/feature_selection.py
- pysr/sr.py
There are a couple remaining lines that print to stdout. This changes those all to use a `logging.getLogger("pysr")` object so that users can more easily filter out printouts.
> use standard library logging

- pysr/export_sympy.py
Following the discussion in https://github.com/MilesCranmer/PySR/discussions/864 .
The order change allows users to override the internal sympy mappings.
> fix: change sympy mappings ordering

- environment.yml
- pyproject.toml
Seems this error didn't show up during testing because one of the test dependencies installed it
> fix: typing extensions dependency

- docs/examples.md
- environment.yml
- pyproject.toml
- pysr/expression_specs.py
- pysr/sr.py
- pysr/test/test_main.py
- pysr/utils.py
This tries to give a helpful warning message to the user for how to upgrade to template expressions.
Suggested by @gm89uk as he found the performance was much better. So there's not much of a point in having a separate class anymore when template expressions are just better.
Care to take a look at the PR and let me know what you think?
> Deprecate ParametricExpressionSpec in favor of TemplateExpressionSpec

- pysr/juliapkg.json
- pysr/param_groupings.yml
- pysr/sr.py
- pysr/test/test_main.py
This adds the `loss_scale` parameter which, when set to `"linear"`, enables negative losses.
I also added a test with a negative-log-likelihood loss with a multi-output template expression.
> Enable negative losses

- .github/workflows/CI.yml
- README.md
- pyproject.toml
Since coveralls-python hasn't updated to Python 3.13, we need to switch to codecov
> ci: switch to codecov

- environment.yml
- pyproject.toml
- pysr/sr.py
- pysr/utils.py
beartype seems to have some builds on conda-forge that are incompatible with older python. These can't be removed without significant effort. But at the end of the day, we were only using the beartype import for one single type (`typing.List`, since Python will eventually deprecate this). Therefore, in order to keep compatibility with old versions, I need to remove beartype as a mandatory requirement. It turns out that `typing_extensions` also has a `List` so I'll just do that. 
Regardless, beartype is still used during testing.
> fix: compat with python 3.8 by removing beartype

- .github/workflows/CI.yml
- .github/workflows/update_backend_version.py
- docs/operators.md
- pyproject.toml
- pysr/_cli/main.py
- pysr/export_sympy.py
- pysr/julia_extensions.py
- pysr/julia_helpers.py
- pysr/juliapkg.json
- pysr/param_groupings.yml
- pysr/sr.py
- pysr/test/__init__.py
- pysr/test/test_autodiff.py
- pysr/test/test_cli.py
- pysr/test/test_dev_pysr.dockerfile
- pysr/test/test_main.py
Features:
- n-ary operators
- support for user-passed "guesses" of equations
- Mooncake and Enzyme support as autodiff backends
- feature node mutation
This also fundamentally changes some of the mutation operators to support the new n-arity operators. For example, a "rotation" of a binary tree has been generalised in such a way that its behavior changes on binary trees as well.
Similarly, the sampling patterns for other mutations has been changed, so as to improve the uniformity of mutations.
TODO:
> Multiple features (update backend to 2.0)

- pysr/sr.py
- pysr/test/test_main.py
This PR implements a feature where, for dataset sizes >= 1000, batching is turned on by default.
Since this is a breaking change, it would only be included in v2.
> feat: automatic batching for big data
