MilesCranmer/PySR

- README.md
- docs/start.md
- pysr/sr.py
- setup.py
- test/test.py
You can now run:
```python
model = PySRRegressor(**params)
model.fit(X, y)
```
Let it run, optionally quit early with `q`, then you can do:
```python
model.fit(X, y)
```
and it will pick up where it left off.
TODO:
> Implement state saving in PySR

- .github/workflows/CI_Windows.yml
- README.md
- example.py
- pysr/sr.py
- pysr/version.py
- test/test.py
This will be for PySR v0.8.0. These settings have been tuned over ~80,000 trials on two hard test problems that PySR had a hard time with originally, as discussed here: https://github.com/MilesCranmer/PySR/discussions/115.
This also includes the adaptive parsimony update in the backend.
> Update PySR default settings

- docs/param_groupings.yml
- pysr/sr.py
- pysr/version.py
This adds two algorithmic improvements in the backend. Adaptive parsimony in particular can be extremely effective at escaping local minima.
> Add optimization-as-mutation, and adaptive parsimony

- pysr/sr.py
- pysr/version.py
The backend update also contains new functionality in the `loss_function` and `elementwise_loss` parameters, but these will not be implemented yet.
> Bump backend version with stream fix; fixes #250

- pysr/version.py
https://github.com/MilesCranmer/SymbolicRegression.jl/releases/tag/v0.15.2
> Bump backend version with data race fix

- pysr/version.py
Fixes warm starts when the loss function or dataset changes. See https://github.com/MilesCranmer/SymbolicRegression.jl/compare/v0.15.2...v0.15.3
> Include backend version with warm start fix

- docs/param_groupings.yml
- pysr/sr.py
- pysr/version.py
Fixes #315 
@TadeuNP want to check if this fixes it for you?
> Pass through `enable_autodiff` parameter

- pysr/sr.py
- pysr/version.py
> Fix compat with old scikit-learn versions

- pysr/sr.py
- pysr/version.py
Also updates backend to v0.21.5
TODO:
> Use unicode in printing without needing to decode

- pysr/export_latex.py
- pysr/export_numpy.py
- pysr/export_sympy.py
- pysr/sr.py
- pysr/test/test.py
(General cleanup to simplify `sr.py`)
TODO:
> Refactor sympy and export functionality

- .github/workflows/CI.yml
- mypy.ini
- pysr/__init__.py
- pysr/denoising.py
- pysr/deprecated.py
- pysr/export_latex.py
- pysr/export_sympy.py
- pysr/feature_selection.py
- pysr/feynman_problems.py
- pysr/sr.py
- pysr/test/test.py
- pysr/utils.py
- Moves the denoising and feature selection utility functions into separate files.
- Fixes some typing issues and sets up `mypy` testing.
- Moves deprecated functions to `deprecated.py`
> Refactor utility functions in `sr.py`

- pysr/export_sympy.py
Add sympy mappings for `logical_and`, `logical_or`, and `relu`.
> Add more piecewise operators

- .github/workflows/CI_docker_large_nightly.yml
Also tests on additional Python versions
> Fix docker CI nightly

- requirements.txt
For safety this adds upper bounds on all dependencies, which we can increment after review
> Enforce upper bound compats

- examples/pysr_demo.ipynb
This updates the colab notebook to use juliaup to install Julia. Makes it way cleaner! And probably more robust.
Also updates the colab demo to use Julia 1.10.
> Update colab notebook to use juliaup

- docs/operators.md
> remove repeated operator

- .github/workflows/update_backend_version.py
- pyproject.toml
- pysr/juliapkg.json
- pysr/test/generate_dev_juliapkg.py
- pysr/test/test_dev_pysr.dockerfile
> Revert GitHub-based registry for backend

- pysr/sr.py
- pysr/test/test_main.py
> test: skip new sklearn checks

- pyproject.toml
- pysr/export_sympy.py
- pysr/test/test_main.py
> fix: pickling of inv

- pyproject.toml
- pysr/expression_specs.py
- pysr/sr.py
- pysr/test/test_main.py
> Fix multi-output template expressions
